name: Create Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        uses: ncipollo/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          bodyFile: "README.md"
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          allowUpdates: true